### ISSUE TITLE
Set a limit on job-template & automatically use the target instance from squest as limit

### ISSUE THREAD

**Issue by brotaxt** [HewlettPackard/squest#525]
**Description of the feature**
I would like to be able to limit the hosts managed or affected by the job-template.

**Describe the solution you'd like**
It would be helpful to have the opportunity to 
- Set a limit for the job-template for the awx-/tower-job. (e.g. When updating a system via squest, I don't wan't to trigger an update on the whole inventory, but on one host)
- Automatically use the target squest-instance as limit-parameter

**Comment by Sispheor** [comment]
Proposed implementation:

- add a new page for each operation that allow to configure all possible override of a job template (all value that have 'prompt on launch'
- update the jinja templating for the"default"' value to allow the full instance instead of only the specs.  (so here the user could set `{{  instance.name }}` in the `limit` field.

**Comment by Sispheor** [comment]
Done and merged in dev branch.
